// OPACITY

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 0.90;

// SHADOW

shadow = false;
shadow-radius = 15;

// FADING

fading = true;
fade-in-step = 0.1;
fade-out-step = 0.1;

// BLUR

blur-method = "dual_kawase";
blur-strength = 4;

blur-background-exclude = [
  "_GTK_FRAME_EXTENTS@:c",
  "QTILE_INTERNAL:32c = 1",
]

//lur = true;
backend = "glx";


// ROUNDED CORNERS

rounded-corners-exclude = [
  "QTILE_INTERNAL:32c = 1"
]

detect-rounded-corners = true;
corner-radius = 10;
round-borders = 1;

// GENERAL

//wintypes:
//{
// // tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
//  dock = { shadow = false; opacity = 1;}
 // dnd = { shadow = false; blur=0 }
 // popup_menu = { opacity = 0.9; blur=0.0; corner-radius: 15}
  //splash = {opacity= 0.9;}
  //dialog = {opacity = 0.9;}
  //notification = {opacity = 0.9; corner-radius: 0;}
  //dropdown_menu = { opacity = 0.8; }
//};

experimental-backends = true;

//_VARIABLE_REFRESH(CARDINAL) = 1
//WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
//WM_TRANSIENT_FOR(WINDOW): window id # 0x1c00005
//WM_HINTS(WM_HINTS):
//	Client accepts input or input focus: True
//_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_MENU, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE
//_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
//WM_CLASS(STRING) = "Steam", "Steam"

